version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: ./build/web.docker
        volumes:
            - ./:/var/www/dockerApp
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: ./build/app.docker
        volumes:
            - ./:/var/www/dockerApp
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"