version: '2'
services:
    web:
        container_name: webserver
        build:
            context: ./build/nginx
        volumes_from:
            - app
        ports:
            - 80:80
        links:
            - app
    app:
        container_name: appserver
        build:
            context: ./build/app
        volumes:
            - ./../:/var/www/justiva
    #        links:
    #            - mysql
    #            - mongodb
    #        depends_on:
    #            - mongodb

    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
            - "MYSQL_DATABASE=justiva_db"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=root_secret"
        ports:
            - "33061:3306"

    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            - "MONGO_INITDB_DATABASE=justiva"
        volumes:
            - ./../storage/app/public/dump:/database/dump
        ports:
            - "27017:27017"